# Where things are
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null
url: http://hainh.gamesen.vn

# Handling Reading
include:      [".htaccess", "CNAME"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:      []

# Conversion
markdown:    kramdown
highlighter: null
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# Outputting
permalink:     /:categories/:year:month:day/:title
paginate_path: /page:num
timezone: Asia/Ho_Chi_Minh
paginate: 15

quiet:    false
defaults: 
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "hainh"
  -
    scope:
      path: "categories"
    values:
      layout: "category-index"
  -
    scope:
      path: "tags"
    values:
      layout: "tag-index"

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false